### ISSUE TITLE
Reload level in gamemanager in `HandleLose`

### ISSUE THREAD

**Issue by RandoNandoz** [Watercooled-Grapes/GMTK-2024#75]

**Comment by Lmh-java** [comment]
Problem: Levels are constantly being loaded and never stops.

Cause: GekkoScript Line 67-70, calling "GameManager.Instance.ReloadLevel();". An async job is run inside a loop.

This is a function call inside an Update function. This would work if the game manager instantly load a new scene, so the Update function will immediately be stopped. However, since we have a cutscene and everything runs asyncly, this Update function will not be stopped immediately, so it will keep running to load new scenes in.

Suggested fix:
Add a flag for whether the game is over or not, and only call **UpdateGameState(GameState)** or **ReloadLevel()** once
```C#
if (gameObject.transform.localPosition.y <= -50 && !_isGameOver)
{
  GameManager.Instance.UpdateGameState(GameState.Lose); // or ReloadLevel();
  _isGameOver = true;
}
```

Also, pls reset the game state to **OnGame** after finish handling win or lose. Although it won't cause any problem rn, but if in the future, someone have some functions to execute only when the game state is on game, this might be problematic. :)
