### ISSUE TITLE
Configure tutorial as index level 0

### ISSUE THREAD

**Issue by RandoNandoz** [Watercooled-Grapes/GMTK-2024#76]
See the enum `CurrentLevel` in `LevelState.cs`, we can use it to manager the indices perhaps? It's to you @Lmh-java.

**Comment by Lmh-java** [comment]
Lemme have a look

**Comment by Lmh-java** [comment]
Currently no, but there is a workaround if we seriously need to use the LevelState.cs indices.

"SceneManager.LoadSceneAsync(index)" is used to switch between scenes asyncly. (It needs to be async, since we need to display the cutscene at the same time and actually give time for the scene to load in the background) This scene index parameter is always the index in the project build setting, as shown below.
<img width="641" alt="image" src="https://github.com/user-attachments/assets/b192aa4f-4b31-41a6-bb62-79902c5f380e">

However, if you want to use your LevelState enum to switch the scene, I guess it would be better to use the SceneManager.LoadSceneAsync(String)" and pass in the scene name. At the same time, you can just configure your enum with the scene name corresponding to each value. I guess this will work perhaps? Or we can just change the build setting and rearrange these scenes into the corresponding index.
